### ISSUE TITLE
Exception thrown at menu when starting up

### ISSUE THREAD

**Issue by CillyCil** [crashbash111/mcdonalds-registersimulator#5]
![image](https://github.com/crashbash111/mcdonalds-registersimulator/assets/47019636/d2522efe-1759-4c8c-830e-a98878d4530a)

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=McDonaldsRegisterSimulator
  StackTrace:
   at WindowsFormsApp1.Form1.set_MainScreen(Int32 value) in D:\Downloads\mcdonalds-registersimulator-master\mcdonalds-registersimulator-master\Form1.cs:line 68

![image](https://github.com/crashbash111/mcdonalds-registersimulator/assets/47019636/394a9191-209b-467c-b49b-55a0fc34911a)

**Comment by crashbash111** [comment]
Hi @minecrafterty1 , you've got to aquire POSDATA on your own from a store to use the simulator. Could you confirm for me that you've got a copy of POSDATA, what region the POSDATA was obtained from, and the age of the files.

You can verify how old the files are by checking under **Posdata** > **Manifest** > **np_61-Store.xml** - under any attribute, there should be a `TimeStamp` property similar to this one: 

![image](https://github.com/crashbash111/mcdonalds-registersimulator/assets/50429378/566ad2c4-0bf8-42b7-bea3-9f1c28ade606)

**Comment by minecrafterty1** [comment]
I have the NpSharp files too if you need them

**Comment by crashbash111** [comment]
> I have the NpSharp files too if you need them

Thanks for this. At work at the moment, but will try and investigate this issue later tonight to see if I can recreate it with a 2022 copy I've got of files from NZ/Australia.
If I can't recreate it, I'll touch base with you if you don't mind sharing the files with me.

**Comment by minecrafterty1** [comment]
Mine should be 2024 copy since we use the latest version in our store

**Comment by crashbash111** [comment]
> Mine should be 2024 copy since we use the latest version in our store

Hi @minecrafterty1 , I can't seem to recreate the issue with the files I've got - the error seems to imply it can't build *any* screens. It could just be that the formatting of the screen.xml is drasitcally different in the states. Any chance you can add me on discord and send me a copy of your posdata so I can see if there's a patch I can do?
Username: joshimonsta

**Comment by crashbash111** [comment]
I've applied some changes to the [branch attached to this issue](https://github.com/crashbash111/mcdonalds-registersimulator/tree/5-exception-thrown-at-menu-when-starting-up). Can you please test and let me know whether you get a warning that no screens are found. If so, I will likely have to inspect your PosData.

**Comment by minecrafterty1** [comment]
I'll test it when I get home in a couple hours

**Comment by minecrafterty1** [comment]
![image](https://github.com/crashbash111/mcdonalds-registersimulator/assets/47019636/c8726a3a-8a50-498d-9199-09a7933c9537)
I got to here

**Comment by minecrafterty1** [comment]
Most things when I click them say action not implemented but I'm assuming that intended rn

**Comment by minecrafterty1** [comment]
And for some reason there are no pictures

**Comment by crashbash111** [comment]
> And for some reason there are no pictures
> 

Facinating seeing the US POS. Chances are they store the images differently - what's inside your posdata > images folder?

**Comment by crashbash111** [comment]
> Most things when I click them say action not implemented but I'm assuming that intended rn

Yeah I've got a basic working KVS in another repository, but just need to finish adding combo support to this one before I add it in. Started in another branch but never got it completed.

**Comment by minecrafterty1** [comment]
> > And for some reason there are no pictures
> 
> Facinating seeing the US POS. Chances are they store the images differently - what's inside your posdata > images folder?

The images are in a zip, but I extracted them too so I have both

**Comment by crashbash111** [comment]
> The images are in a zip, but I extracted them too so I have both

That's interesting - the NZ one they stopped zipping images a while ago so I removed the unzip functionality.
Putting your images inside of a `POS_images` subfolder in the images folder should make it work temporarily now.

What was the name of the zipped images? `repository.1024x768.zip` or something similar?

**Comment by crashbash111** [comment]
> > > And for some reason there are no pictures
> > 
> > 
> > Facinating seeing the US POS. Chances are they store the images differently - what's inside your posdata > images folder?
> 
> The images are in a zip, but I extracted them too so I have both

As this issue has been fixed, I will close this issue and open a new one for the images. I may have to add some code that will scan the image directory for folders and zip files depending on what copy of POSDATA is used.
